sudo "emerge -n =net-libs/nodejs-0.10.28"
sudo "eselect nodejs set 0.10.28"
sudo "ln -nfs /opt/nodejs/0.10.28 /opt/nodejs/current"
sudo "ln -nfs /opt/nodejs/current/bin/node /usr/bin/node"
sudo "ln -nfs /opt/nodejs/current/bin/npm /usr/bin/npm"
